### ISSUE TITLE
Docker bench for version 18.06.1-ce

### ISSUE THREAD

**Issue by VineethReddy02** [aquasecurity/docker-bench#38]
Can we have docker bench for the newer version of docker and does aquasec has any slack or gitter channel for discussions on various aquasec open source projects.

**Comment by daniyalj** [comment]
Any update on this? We are running into the same problems

**Comment by lizrice** [comment]
We follow the CIS Docker Benchmark and I don't believe there has been a newer release yet (which means that the current set of tests is still up-to-date)

We don't have a Slack / Gitter at this point but I will look at getting something set up.

**Comment by roman-in-arctiq** [comment]
[Your check](https://github.com/aquasecurity/docker-bench/blob/master/cfg/17.06/definitions.yaml) fails if the syestem does not have  the `--disable-legacy-registry` set.
```
- id: 2.13
    description: "Ensure operations on legacy registry (v1) are Disabled (Scored)"
    audit: ps -ef | grep dockerd
    tests:
      test_items:
      - flag: "--disable-legacy-registry"
        set: true
    remediation: |
      Start the docker daemon as below:
      dockerd --disable-legacy-registry
    scored: true
```
Here is the info [from Docker](https://docs.docker.com/engine/deprecated/#--disable-legacy-registry-override-daemon-option) 

> The --disable-legacy-registry flag was disabled in Docker 17.12 and will print an error when used. For this error to be printed, the flag itself is still present, but hidden. The flag will be removed in Docker 18.03.

[Dockers own bench](https://github.com/docker/docker-bench-security/blob/master/tests/2_docker_daemon_configuration.sh) uses conditionals to check for the version
```
check_2_13() {
  docker_version=$(docker version | grep -i -A2 '^server' | grep ' Version:' \
    | awk '{print $NF; exit}' | tr -d '[:alpha:]-,.' | cut -c 1-4)
  totalChecks=$((totalChecks + 1))

  id_2_13="2.13"
  desc_2_13="Ensure operations on legacy registry (v1) are Disabled"
  check_2_13="$id_2_13  - $desc_2_13"
  starttestjson "$id_2_13" "$desc_2_13"

  if [ "$docker_version" -lt 1712 ]; then
    if get_docker_configuration_file_args 'disable-legacy-registry' | grep 'true' >/dev/null 2>&1; then
      pass "$check_2_13"
      resulttestjson "PASS"
      currentScore=$((currentScore + 1))
    elif get_docker_effective_command_line_args '--disable-legacy-registry' | grep "disable-legacy-registry" >/dev/null 2>&1; then
      pass "$check_2_13"
      resulttestjson "PASS"
      currentScore=$((currentScore + 1))
    else
      warn "$check_2_13"
      resulttestjson "WARN"
      currentScore=$((currentScore - 1))
    fi
  else
    desc_2_13="$desc_2_13 (Deprecated)"
    check_2_13="$id_2_13  - $desc_2_13"
    info "$check_2_13"
    resulttestjson "INFO"
  fi
}
```

@lizrice @daniyalj
